name: ci
on:
  push:
    tags:
      - 'v*'
      
jobs:
  buildImg:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      - name: shelltest
        run: |
            free -h
            pwd
            ls
            echo '${{ toJSON(github) }}'
            git clone https://github.com/openresty/openresty-systemtap-toolkit.git
            git clone https://github.com/openresty/stapxx.git
            git clone https://github.com/brendangregg/FlameGraph.git
            
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/openresty:${{ github.ref_name }}
  applyImg:
    needs: buildImg
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
    
    - name: change app img tag
      run: |
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "
          cd ${{ secrets.APP_DIR }}
          sed -ir "/openresty/s/v[0-9].[0-9]$/'${{ github.ref_name }}'/"  docker-compose.yml
          docker-compose up -d 
        "
    
  
          
    
